Add Borealis Theme
revoltchat/themes pull request #21
Opened 2021-11-21 16:50 UTC by QazCetelic

2021-11-21 16:52 UTC, QazCetelic commented
![Settings-Appearance](https://user-images.githubusercontent.com/51381523/142771347-4e784d04-4bb0-4f4c-b58a-99fb7a4253f3.png)
![Channel-Preview](https://user-images.githubusercontent.com/51381523/142771350-5c25e0a9-45b0-4c54-8f5a-fc960a151184.png)

2021-11-22 09:44 UTC, aeristhy commented
I should link you up to this comment right [here](https://github.com/revoltchat/themes/pull/2#issuecomment-955798618)

-----------------

This is fine for the most part but there are two issues with the custom background:

- Hot-linking to external third party service.

- I'd probably need to have a license to use this artwork? Since I'd imagine it's protected under copyright law.

Not sure how to go about resolving either.

2021-11-22 10:05 UTC, QazCetelic commented
The image is loaded from the Pixabay CDN, Pixabay provides free images & royalty free stock. The image is therefore licensed under the [Pixabay License](https://pixabay.com/service/license/), which allows usage like this even without attribution.

I can see how the hot linking is an issue though, would it be possible to allow adding an `media` folder to a theme to store content like this?

2021-11-22 10:13 UTC, QazCetelic commented
I just checked it and the revolt servers will have to store the media.
> NO HOTLINKING - what does that mean?
If you want to show Pixabay media on your website, please upload them to your server. Pixabay media URLs don't work on external sites.

2021-11-22 11:05 UTC, aeristhy commented
I see, this should fix issues Insert was worried about(I think)

2021-12-30 15:16 UTC, QazCetelic commented
> I see, this should fix issues Insert was worried about(I think)

I opened an issue (#24) to add a media folder so that this theme can be added.

2022-01-06 14:28 UTC, QazCetelic commented
The background image is embedded into the CSS now.

2022-01-12 10:12 UTC, QazCetelic commented
@insertish I think it's valid now, I found a work-around without needing the media folder.

2022-01-14 16:34 UTC, insertish commented
This does create a new problem in the fact that the custom CSS file is 127 kB now.

I would either:
- Wait for discovery system to be changed to only load preset file for preview.
- Wait for media folder issue to be resolved.
- Host the image on Revolt; upload to Saved Notes.

2022-01-20 11:26 UTC, QazCetelic commented
The image is now hosted on Revolt.

2022-01-20 12:13 UTC, Rexogamer requested changes
Few minor points:

2022-01-20 12:13 UTC, Rexogamer commented on data/borealis/Custom.css
> +    --northern-lights-darkend: linear-gradient(rgba(0, 0, 0, 0.65),rgba(0, 0, 0, 0.65)), var(--northern-lights);
Minor typo here:
```suggestion
    --northern-lights-darkened: linear-gradient(rgba(0, 0, 0, 0.65),rgba(0, 0, 0, 0.65)), var(--northern-lights);
```

2022-01-20 12:13 UTC, Rexogamer commented on data/borealis/Custom.css
> +    background-image: var(--northern-lights-darkend);
```suggestion
    background-image: var(--northern-lights-darkened);
```

2022-01-20 12:13 UTC, Rexogamer commented on data/borealis/Custom.css
> +    background-image: var(--northern-lights-darkend);
```suggestion
    background-image: var(--northern-lights-darkened);
```

2022-01-20 12:13 UTC, Rexogamer commented on data/borealis/Preset.toml
> +
You should probably add a theme version:
```suggestion
version = "1.0.0"
```

2022-02-02 11:38 UTC, Rexogamer approved these changes

2022-02-18 07:10 UTC, QazCetelic commented
@insertish It should be valid now

2022-05-05 09:03 UTC, QazCetelic commented
@insertish will this be merged?

2023-01-18 23:19 UTC, Rexogamer commented
The custom CSS will likely need to be updated

2025-02-13 09:20 UTC, DeclanChidlow commented
Closing as stale. You are welcome to resubmit your theme if you still wish for it to be included.

2025-02-13 09:20 UTC, closed without merging