Add Social Classic theme
revoltchat/themes pull request #76
Opened 2023-06-23 22:56 UTC by DragShot

## Please make sure to check the following tasks before opening and submitting a PR

* [X] I understand and have followed the [contribution guide](https://github.com/revoltchat/revolt/discussions/282)
* [X] I have tested my changes locally and they are working as intended
* [X] These changes do not have any notable side effects on other Revolt projects

# Social Classic Theme for Revite

A theme inspired in social websites from the 2010s, mixing light and dark elements with a prominent use of a primary color. Said color can be easily customized through the accent color picker in the Appearance settings.

This theme includes custom CSS.

## Screenshots

### Web/Desktop

![Preview Image](https://autumn.revolt.chat/attachments/FUom-OppM7HYJAZsicYzl43Fa99GU4ZUOt8zyQt30c/desktop-friends.png)

![Preview Image](https://autumn.revolt.chat/attachments/ktdsxbhkn15CYbcNoj3-QRcAOUgnc-BejTImOJsNHx/desktop-server.png)

![Preview Image](https://autumn.revolt.chat/attachments/pqtGeHzAVencATD4sB4zxevdTK1oTQ63qugy70FFrB/desktop-settings.png)

![Preview Image](https://autumn.revolt.chat/attachments/hbS_n44lMg7AScM_ZbFr9_5Tbj52uC0E10_PEykgB9/desktop-profiles.png)

### Mobile

![Preview Image](https://autumn.revolt.chat/attachments/NaMcGSqmPavB_l6p4PqJpNR0yANK09AYZyhJo2bYFX/mobile.png)

### Primary colors

![Preview Image](https://autumn.revolt.chat/attachments/p4VxnTdp2V-Xc0uM8QsKykm0TCEmEnpRQaPLciK0TJ/colors.png)

2023-07-01 18:27 UTC, Rexogamer requested changes

2023-07-01 18:27 UTC, Rexogamer commented on data/social-classic/Preset.toml
> +description = "A mixture of light, dark and a primary color of your preference, inspired in social websites from the 2010s."
```suggestion
description = "A mixture of light, dark and a primary color of your preference, inspired by social websites from the 2010s."
```

2023-07-01 18:27 UTC, Rexogamer commented on data/social-classic/Preset.toml
> +version = "1.0.0"
```suggestion
version = "v1.0.0"
```

2023-07-01 18:29 UTC, Rexogamer approved these changes

2023-07-01 18:29 UTC, merged

2023-07-02 23:15 UTC, DragShot commented
Thanks!