feat: add text theme
revoltchat/themes pull request #95
Opened 2024-07-17 19:24 UTC by gaygoblin

# text
a TUI theme based on the one of the same name from Spicetify.
Most of the code was written by me. 
This is my first "*big*" CSS project, and I really liked making it :3
#
- [x] I understand and have followed the [contribution guide](https://github.com/revoltchat/.github/blob/master/.github/CONTRIBUTING.md)
- [x] I have tested my changes locally and they are working as intended

2024-07-24 18:37 UTC, Rexogamer requested changes

2024-07-24 18:37 UTC, Rexogamer commented on data/text/preset.toml
rename this to `Preset.toml` (capitalised)

2024-07-26 03:51 UTC, gaygoblin commented on data/text/preset.toml
Done.

2024-07-28 03:07 UTC, Rexogamer commented on data/text/Preset.toml
> +desc = "a tui theme based on the "text" theme from spicetify"
escape the quotes:

```suggestion
desc = "a tui theme based on the \"text\" theme from spicetify"
```

2024-07-28 03:08 UTC, Rexogamer commented on data/text/Preset.toml
> +primary-header: "#1e1e1e"
```suggestion
primary-header = "#1e1e1e"
```

2024-08-03 19:50 UTC, gaygoblin commented
why isnt the changes requested thing done i resolved the change

2024-08-04 00:28 UTC, Rexogamer requested changes

2024-08-04 00:28 UTC, Rexogamer commented on data/text/Preset.toml
> +desc = "a tui theme based on the \"text\" theme from spicetify"
```suggestion
description = "a tui theme based on the \"text\" theme from spicetify"
```

2024-08-05 01:42 UTC, gaygoblin commented
okay! everything _should_ be fine now.. i double checked the preset.toml again and it seems good!

2024-08-05 19:48 UTC, Rexogamer commented
still not quite, but it's getting closer. you might want to look at [this](https://github.com/revoltchat/themes/blob/master/data/amethyst/Preset.toml) for a working example - note the use of sections instead of certain key names (e.g. `[variables.primary]` with a `background` key instead of `primary-background`).

alternatively, you can use [this tool](https://rexovolt.github.io/revolt-theme-tools/) I made to convert the original JSON theme into a working TOML file. hope that helps :3

2024-09-09 18:09 UTC, closed without merging